### ISSUE TITLE
Group Formation Problems

### ISSUE THREAD

**Issue by stefonrose** [codepath/ios_issues#1]
Whenever I try to lock or save groups in the Group Formation window it doesn't work. If I were to rearrange the groups and then press save, refreshing the page resets everything back to how it originally was.

**Comment by chieger** [comment]
@stefonrose Can you try logging out and back in to the course portal and then accessing the Group Formation tool once again? I believe you should now have access to edit.

**Comment by chieger** [comment]
Resolved 🚀
