### ISSUE TITLE
README file missing for Unit 5 Lab - Parse Chat

### ISSUE THREAD

**Issue by ghost** [codepath/ios_issues#2]
Greetings,

The README file for Lab 5 - Parse Chat is missing.

Here is one that I gave to our students to use:

https://gist.githubusercontent.com/petecsn/4b964d9add18380e2c5c73b0782696ee/raw/ae41930efbbfb12825ebfb141b402286a2963b6e/README.md

Thank you

**Comment by timothy1ee** [comment]
Thanks, I moved this into our courses content repo, and I added a link to the readme template on the lab page.
