### ISSUE TITLE
README file missing for Unit 6 Lab - Photo Map

### ISSUE THREAD

**Issue by ghost** [codepath/ios_issues#3]
Greetings

The README file for the Unit 6 Lab - Photo Map is missing.

Here is one that I gave to our students to use:

https://gist.githubusercontent.com/petecsn/3994448ef2a03ea36362e0c1e306f688/raw/5f9c5b491e2b3a7a64ff2101b58edfd8201987c6/README.md

Thank you

**Comment by timothy1ee** [comment]
Thanks, I moved this into our courses content repo, and I added a link to the readme template on the lab page.
